### ISSUE TITLE
DCHDMI nukes whole HDMI Control (HDMI-CEC) network

### ISSUE THREAD

**Issue by ACiDxCHRiST** [citrus3000psi/DCHDMI-Hardware#4]
As soon as the HDMI cable is attached to the Dreamcast, the whole HDMI-CEC network goes down. Devices are not able to identify each other (ie. Receiver and TV), button presses on one device's remote are not transferred to the other devices in the chain (ie. changing Receiver volume with TV remote), Standby Sync does not function (ie. Turning on/off Receiver+Android TV Box automatically when TV is turned on/off or any other combination depending on which device is turned on/off), and Automatic Input Switching does not function (ie. Receiver automatically changes to Android TV input when Android TV box is powered on.)

It does not matter if the Dreamcast is powered or not, simply making the mechanical connection takes the whole network down. I initially noticed this with my default setup which is with a single HDMI cable from the output of the Receiver to an input on the TV. Six other HDMI Devices + the Dreamcast are connected to the seven inputs of my receiver. I then tested it with an abbreviated network using just the TV (to rule out any weirdness that might be specific to my Receiver). NVIDIA Shield TV connected to Input 1 of the TV and a 2nd HDMI cable connected to Input 2 of the TV. I verified that all the HDMI-CEC functions listed above worked (ie. Standby Sync, Volume Control, Navigating Android TV interface with TV Remote etc.). As soon as I connected the 2nd HDMI cable to the Dreamcast, all HDMI-CEC functionality ceased between the NVIDIA Shield TV and the TV. And interesting to note, as soon as I disconnected the HDMI cable from the Dreamcast, all of the "Up, Down, Left, Right" button presses that I had done on the TV Remote, suddenly played back rapidly in order on the Android TV interface.

I should also mention that this does not appear to effect HDMI Video/Audio or metadata transmission. Also of note, I have an N64 UltraHDMI that does not cause any issues like this.

Other Details:
TV: Samsung Q6FN
DCHDMI: Install done by citrus3000psi (VA1, USB-GDROM with Reset)

**Comment by citrus3000psi** [comment]
Thanks for pointing this issue out.  The CEC pin on the HDMI grounded and is what is causing these problems.  There are three ways to fix, ranging from hardest to easiest.

-Remove the HDMI connector and cut the trace to CEC and Reinstall HDMI connector (not recommended)
-Lift pin 14 on the HDMI connector.  Difficult to do, but is possible.
-Purchase a CEC Less Adapter like this one:  https://www.amazon.com/Lindy-HDMI-Adapter-Female-41232/dp/B00DL48KVI/

All future revisions will not have this issue.  Sorry for any inconvenience everybody.

**Comment by ACiDxCHRiST** [comment]
I went ahead and ordered the CEC Less Adapter, but reading through the reviews for the product and then researching the HDMI pinout, it looks like CEC is on Pin 13. You mentioned lifting Pin 14 on the connector; so I just wanted to confirm, do you lift Pin 13 or 14 on the connector? (if you wanted to use that method)

-Edit
Disregard, I see now that CEC is on Pin 14 of the Mini HDMI Connector (Type C) and is on Pin 13 of a regular HDMI Connector (Type A)

So I know what needs to be done depending upon where you are making the modification.

**Comment by mario-64** [comment]
I can confirm the CEC-less adapter resolves the issue. As a workaround I mean.
