### ISSUE TITLE
Details on flex PCB

### ISSUE THREAD

**Issue by wmi-0** [citrus3000psi/DCHDMI-Hardware#5]
First of all a huge thanks for releasing the DCHDMI hardware designs as open source!

Can you provide some details on how the flex cable should be manufactured?
From the connector I assume 0.3mm thickness ~~0.1mm thickness with a 0.2mm plastic stiffener on the bottom~~, 0.5 oz copper?

**Comment by citrus3000psi** [comment]
The FFC connector needs to be ~.3mm   I get the flex made in .18mm with the stiffener at .1mm  With the adhesive its a shy over .3mm  

.5oz copper works, but the place I uses offers 1oz at no extra cost so I always choose that
