### ISSUE TITLE
A slight misalignment of the dc digital board to the left will cause a short when closing back the shielding

### ISSUE THREAD

**Issue by mathieulh** [citrus3000psi/DCHDMI-Hardware#6]
A slight misalignment of the dc digital board to the left (about a degree or less) will cause a short when closing back the shielding, no amount of isolation will fix it (I literally taped the board at one point), the short will cause PSUs without protections (including the original one) to eventually start sparking, then burning. (yes, this happened to me!) Realigning the board fixed it, but this design makes it literally a fire harzard if the install is slightly off (we are talking a degree or less shift to the left). Fortunately for me the Pico PSU I usually use has protections against short or things could have gone really bad, the original PSU sparked all over and had a very bad burnt smell when I tried it for less than 2 seconds.

**Comment by citrus3000psi** [comment]
Can you confirm the vinyl backing is covering up the esp2866 WiFi solder points. One of the two bottom points is 3.3v and if not properly isolated then a direct short can happen.

Also can you confirm you installed the plastic protector that goes under the PSU? If this is missing that can cause the PSU to spark and short out like you are experiencing.

I have rechecked the alignment and there is no danger of the board making contact with anything.

![234D7876-9CFE-4B0D-A1C3-C74CC6D32B29](https://user-images.githubusercontent.com/2659300/85934712-0de62780-b8b5-11ea-87b9-e6f722467b98.jpeg)

**Comment by citrus3000psi** [comment]
I just relooked at this. There is nothing remotely close to touching the board in either direction.

![234D7876-9CFE-4B0D-A1C3-C74CC6D32B29](https://user-images.githubusercontent.com/2659300/85934712-0de62780-b8b5-11ea-87b9-e6f722467b98.jpeg)

**Comment by mathieulh** [comment]
Sorry for the late reply, yes I can confirm the vinyl is on, I also looked and did not see anything that did contact myself, I even taped the whole board, the only thing I can think of is the screw itself. Whenever it was shifted to the left it caused a short.

**Comment by citrus3000psi** [comment]
Your cause is likely from not reinstalling the plastic protector piece under the PSU when using the original.

"the original PSU sparked all over and had a very bad burnt smell when I tried it for less than 2 seconds."

Its impossible for the PSU to spark on the secondary side as this would have never been allowed in Europe, even in 1998.  The PSU has a built in fuse which wouldn't allow this.  It appears your primary side (240v) shorted because of the missing plastic piece that goes under the PSU.  This has happened to other users as well.

**Comment by mathieulh** [comment]
The plastic was below the PSU, I also tested a pico psu (that's what I used originally), and it detected the short (and would cut power to the board), whereas the fuse on the PSU did not trigger (I was using a 220V PSU if tthat information helps).

**Comment by citrus3000psi** [comment]
If the primary side of the PSU shorted, than it could cause all sorts of havok in the system so after switching to the Pico, the damage was already done.

Again, Its impossible for the PSU to short on the secondary side and throw sparks.  This is something the DCHDMI could not have caused no matter what.  And out of the 1500 installs, you happen to the be the only one.  If the unit only need to be barely moved and it would blow the system there would be numerous reports.

And to restate the fact there is an image with the DCHDMI board showing it cannot short against anything.

**Comment by mathieulh** [comment]
All I can tell is the short happened and was very consistent, I am not going to cause it on purpose for obvious reasons. The part of the PSU that had the burnt smell was the bottom part (the one closest to the power button). Again, the plastic part was definitely under the PSU, heck I put it even when I use the pico psu even though that's typically useless.

I suspect one of the mounting screws may have caused the short.
